/**
 * File-backed persistence: the pre-loaded library datasets (read-only) and
 * per-RFP workspaces under data/workspaces/<id>/. Zero external services so
 * the prototype runs anywhere node runs.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import type {
  BidOutcome,
  CapabilityRecord,
  CompanyProfile,
  EvaluationCriterion,
  Workspace,
} from "./types";

const DATA_DIR = path.join(process.cwd(), "data");
const LIBRARY_DIR = path.join(DATA_DIR, "library");
const WORKSPACES_DIR = path.join(DATA_DIR, "workspaces");

/* ------------------------------------------------------------------ */
/* Library datasets                                                    */
/* ------------------------------------------------------------------ */

async function readJson<T>(file: string): Promise<T> {
  const raw = await fs.readFile(file, "utf-8");
  return JSON.parse(raw) as T;
}

export interface Library {
  capabilities: CapabilityRecord[];
  bidHistory: BidOutcome[];
  criteria: EvaluationCriterion[];
  profile: CompanyProfile;
}

let _library: Library | null = null;

export async function loadLibrary(): Promise<Library> {
  if (_library) return _library;
  const [capabilities, bidHistory, criteria, profile] = await Promise.all([
    readJson<CapabilityRecord[]>(path.join(LIBRARY_DIR, "capability_library.json")),
    readJson<BidOutcome[]>(path.join(LIBRARY_DIR, "bid_history.json")),
    readJson<EvaluationCriterion[]>(path.join(LIBRARY_DIR, "evaluation_criteria.json")),
    readJson<CompanyProfile>(path.join(LIBRARY_DIR, "company_profile.json")),
  ]);
  _library = { capabilities, bidHistory, criteria, profile };
  return _library;
}

/* ------------------------------------------------------------------ */
/* Workspaces                                                          */
/* ------------------------------------------------------------------ */

function workspaceDir(id: string): string {
  // ids are generated by us; guard anyway against path tricks
  if (!/^ws_[a-z0-9]+$/.test(id)) throw new Error(`Invalid workspace id: ${id}`);
  return path.join(WORKSPACES_DIR, id);
}

export function newWorkspaceId(): string {
  return `ws_${Date.now().toString(36)}${crypto.randomBytes(3).toString("hex")}`;
}

export async function saveWorkspace(ws: Workspace): Promise<void> {
  const dir = workspaceDir(ws.id);
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(path.join(dir, "workspace.json"), JSON.stringify(ws, null, 2));
}

export async function saveWorkspaceFile(
  id: string,
  fileName: string,
  data: Buffer | string,
): Promise<string> {
  const dir = workspaceDir(id);
  await fs.mkdir(dir, { recursive: true });
  const safe = path.basename(fileName);
  const target = path.join(dir, safe);
  await fs.writeFile(target, data);
  return target;
}

export async function readWorkspaceText(id: string): Promise<string> {
  return fs.readFile(path.join(workspaceDir(id), "extracted.txt"), "utf-8");
}

export async function getWorkspace(id: string): Promise<Workspace | null> {
  try {
    return await readJson<Workspace>(path.join(workspaceDir(id), "workspace.json"));
  } catch {
    return null;
  }
}

export async function listWorkspaces(): Promise<Workspace[]> {
  try {
    const entries = await fs.readdir(WORKSPACES_DIR);
    const workspaces = await Promise.all(
      entries.filter((e) => e.startsWith("ws_")).map((e) => getWorkspace(e)),
    );
    return workspaces
      .filter((w): w is Workspace => w !== null)
      .sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  } catch {
    return [];
  }
}

export async function deleteWorkspace(id: string): Promise<void> {
  await fs.rm(workspaceDir(id), { recursive: true, force: true });
}
